-- Pedidos de capa personalizada (módulo Comercial)
-- Tabelas criadas automaticamente pela API na primeira chamada.
-- Este script serve para ambiente/manual e documentação.

IF OBJECT_ID(N'dbo.COM_PEDIDO_CAPA', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.COM_PEDIDO_CAPA (
        ID                INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        NUMERO_PEDIDO     NVARCHAR(40)  NULL,
        CLIENTE           NVARCHAR(200) NOT NULL,
        CONTATO           NVARCHAR(120) NULL,
        TELEFONE          NVARCHAR(40)  NULL,
        MODELO_ID         NVARCHAR(80)  NOT NULL,
        MODELO_NOME       NVARCHAR(200) NOT NULL,
        QUANTIDADE        INT           NOT NULL CONSTRAINT DF_COM_PEDIDO_CAPA_QTD DEFAULT (1),
        DATA_PEDIDO       DATE          NOT NULL,
        DATA_NECESSIDADE  DATE          NOT NULL,
        PRIORIDADE        NVARCHAR(20)  NOT NULL CONSTRAINT DF_COM_PEDIDO_CAPA_PRI DEFAULT ('NORMAL'),
        OBSERVACAO        NVARCHAR(MAX) NULL,
        STATUS            NVARCHAR(20)  NOT NULL CONSTRAINT DF_COM_PEDIDO_CAPA_ST DEFAULT ('RASCUNHO'),
        VENDEDOR          NVARCHAR(100) NOT NULL,
        PRODUCAO_POR      NVARCHAR(100) NULL,
        ENVIADO_POR       NVARCHAR(100) NULL,
        DT_ENVIO_PRODUCAO DATETIME      NULL,
        DT_PRODUZIDO      DATETIME      NULL,
        DT_ENVIADO        DATETIME      NULL,
        CRIADO_EM         DATETIME      NOT NULL CONSTRAINT DF_COM_PEDIDO_CAPA_CRI DEFAULT (GETDATE()),
        ATUALIZADO_EM     DATETIME      NOT NULL CONSTRAINT DF_COM_PEDIDO_CAPA_ATU DEFAULT (GETDATE())
    );
    CREATE INDEX IX_COM_PEDIDO_CAPA_STATUS ON dbo.COM_PEDIDO_CAPA (STATUS, DATA_NECESSIDADE);
    CREATE INDEX IX_COM_PEDIDO_CAPA_CLIENTE ON dbo.COM_PEDIDO_CAPA (CLIENTE);
END
GO

IF OBJECT_ID(N'dbo.COM_PEDIDO_CAPA_ANEXO', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.COM_PEDIDO_CAPA_ANEXO (
        ID            INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        PEDIDO_ID     INT           NOT NULL,
        TIPO          NVARCHAR(20)  NOT NULL,
        NOME_ARQUIVO  NVARCHAR(255) NULL,
        MIME          NVARCHAR(80)  NOT NULL,
        CONTEUDO      VARBINARY(MAX) NOT NULL,
        TAMANHO       INT           NOT NULL,
        CRIADO_EM     DATETIME      NOT NULL CONSTRAINT DF_COM_PEDIDO_ANEXO_CRI DEFAULT (GETDATE()),
        CRIADO_POR    NVARCHAR(100) NULL,
        CONSTRAINT FK_COM_PEDIDO_ANEXO_PEDIDO
            FOREIGN KEY (PEDIDO_ID) REFERENCES dbo.COM_PEDIDO_CAPA (ID)
    );
    CREATE UNIQUE INDEX UQ_COM_PEDIDO_ANEXO_TIPO ON dbo.COM_PEDIDO_CAPA_ANEXO (PEDIDO_ID, TIPO);
END
GO

IF OBJECT_ID(N'dbo.COM_PEDIDO_CAPA_LOG', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.COM_PEDIDO_CAPA_LOG (
        ID              INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        PEDIDO_ID       INT           NOT NULL,
        ACAO            NVARCHAR(40)  NOT NULL,
        STATUS_ANTERIOR NVARCHAR(20)  NULL,
        STATUS_NOVO     NVARCHAR(20)  NULL,
        USUARIO         NVARCHAR(100) NOT NULL,
        DETALHE         NVARCHAR(MAX) NULL,
        CRIADO_EM       DATETIME      NOT NULL CONSTRAINT DF_COM_PEDIDO_LOG_CRI DEFAULT (GETDATE()),
        CONSTRAINT FK_COM_PEDIDO_LOG_PEDIDO
            FOREIGN KEY (PEDIDO_ID) REFERENCES dbo.COM_PEDIDO_CAPA (ID)
    );
    CREATE INDEX IX_COM_PEDIDO_LOG_PEDIDO ON dbo.COM_PEDIDO_CAPA_LOG (PEDIDO_ID, CRIADO_EM);
END
GO
