-- De/para de capas personalizadas:
-- COD_PERSO  = código que chega do pedido/loja
-- COD_ORIGEM = código físico que a produção baixa e personaliza

IF OBJECT_ID(N'dbo.PROD_CAPA_DEPARA', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.PROD_CAPA_DEPARA (
        ID              INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        COD_ORIGEM      NVARCHAR(20)  NOT NULL,
        COD_PERSO       NVARCHAR(20)  NOT NULL,
        LINHA           NVARCHAR(40)  NULL,
        DESCRICAO       NVARCHAR(300) NULL,
        ATIVO           BIT           NOT NULL CONSTRAINT DF_CAPA_DEPARA_ATV DEFAULT (1),
        ATUALIZADO_EM   DATETIME      NOT NULL CONSTRAINT DF_CAPA_DEPARA_ATU DEFAULT (GETDATE()),
        ATUALIZADO_POR  NVARCHAR(100) NULL
    );
    CREATE UNIQUE INDEX UQ_CAPA_DEPARA_PERSO ON dbo.PROD_CAPA_DEPARA (COD_PERSO);
    CREATE INDEX IX_CAPA_DEPARA_ORIGEM ON dbo.PROD_CAPA_DEPARA (COD_ORIGEM);
    CREATE INDEX IX_CAPA_DEPARA_LINHA ON dbo.PROD_CAPA_DEPARA (LINHA);
END
GO

IF COL_LENGTH('dbo.COM_PEDIDO_CAPA', 'COD_PERSO') IS NULL
    ALTER TABLE dbo.COM_PEDIDO_CAPA ADD COD_PERSO NVARCHAR(20) NULL;
IF COL_LENGTH('dbo.COM_PEDIDO_CAPA', 'COD_ORIGEM') IS NULL
    ALTER TABLE dbo.COM_PEDIDO_CAPA ADD COD_ORIGEM NVARCHAR(20) NULL;
IF COL_LENGTH('dbo.COM_PEDIDO_CAPA', 'LINHA_PRODUTO') IS NULL
    ALTER TABLE dbo.COM_PEDIDO_CAPA ADD LINHA_PRODUTO NVARCHAR(40) NULL;
GO
