-- Mapa visual de endereços (estantes + posições).
-- Também é criado automaticamente na primeira chamada da API.

IF OBJECT_ID(N'dbo.TB_MAPA_ESTANTE', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.TB_MAPA_ESTANTE (
        ID            INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        CODIGO        NVARCHAR(40)  NOT NULL UNIQUE,
        NOME          NVARCHAR(80)  NOT NULL,
        TIPO          NVARCHAR(20)  NOT NULL CONSTRAINT DF_MAPA_EST_TIPO DEFAULT ('RACK'),
        ORDEM         INT           NOT NULL CONSTRAINT DF_MAPA_EST_ORD DEFAULT (1),
        COLUNAS       INT           NOT NULL CONSTRAINT DF_MAPA_EST_COL DEFAULT (30),
        ATIVO         BIT           NOT NULL CONSTRAINT DF_MAPA_EST_ATV DEFAULT (1),
        ATUALIZADO_EM DATETIME      NOT NULL CONSTRAINT DF_MAPA_EST_ATU DEFAULT (GETDATE())
    );
END
GO

IF OBJECT_ID(N'dbo.TB_MAPA_POSICAO', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.TB_MAPA_POSICAO (
        ID            INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        ESTANTE_ID    INT           NOT NULL,
        ENDERECO      NVARCHAR(40)  NOT NULL,
        LINHA         INT           NOT NULL CONSTRAINT DF_MAPA_POS_LIN DEFAULT (1),
        COL_INICIO    INT           NOT NULL CONSTRAINT DF_MAPA_POS_COL DEFAULT (1),
        COLSPAN       INT           NOT NULL CONSTRAINT DF_MAPA_POS_SPN DEFAULT (1),
        ATIVO         BIT           NOT NULL CONSTRAINT DF_MAPA_POS_ATV DEFAULT (1),
        ATUALIZADO_EM DATETIME      NOT NULL CONSTRAINT DF_MAPA_POS_ATU DEFAULT (GETDATE()),
        CONSTRAINT FK_MAPA_POS_ESTANTE FOREIGN KEY (ESTANTE_ID) REFERENCES dbo.TB_MAPA_ESTANTE (ID),
        CONSTRAINT UQ_MAPA_POS_ENDERECO UNIQUE (ENDERECO)
    );
    CREATE INDEX IX_MAPA_POS_ESTANTE ON dbo.TB_MAPA_POSICAO (ESTANTE_ID, LINHA, COL_INICIO);
END
GO
