-- Cria tabela de configurações do inventário cíclico
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TB_CONFIG_INVENTARIO]') AND type in (N'U'))
BEGIN
    CREATE TABLE [dbo].[TB_CONFIG_INVENTARIO] (
        [ID_CONFIG] INT IDENTITY(1,1) PRIMARY KEY,
        [BLOCO1_QTD_ITENS] INT DEFAULT 10,
        [BLOCO1_DIAS_MOVIMENTACAO] INT DEFAULT 21,
        [BLOCO2_QTD_ITENS] INT DEFAULT 10,
        [BLOCO2_ACURACIDADE_MIN] FLOAT DEFAULT 95,
        [BLOCO3_QTD_ITENS] INT DEFAULT 3,
        [USUARIO_ALTERACAO] NVARCHAR(100),
        [DT_ALTERACAO] DATETIME DEFAULT GETDATE()
    );
    PRINT 'Tabela TB_CONFIG_INVENTARIO criada com sucesso!';
    
    -- Insere configuração padrão
    INSERT INTO [dbo].[TB_CONFIG_INVENTARIO] 
    (BLOCO1_QTD_ITENS, BLOCO1_DIAS_MOVIMENTACAO, BLOCO2_QTD_ITENS, BLOCO2_ACURACIDADE_MIN, BLOCO3_QTD_ITENS, USUARIO_ALTERACAO)
    VALUES (10, 21, 10, 95, 3, 'SISTEMA');
    PRINT 'Configuração padrão inserida!';
END
ELSE
BEGIN
    PRINT 'Tabela TB_CONFIG_INVENTARIO já existe!';
END

-- Verifica a criação
SELECT COUNT(*) AS TOTAL_REGISTROS FROM [dbo].[TB_CONFIG_INVENTARIO];
SELECT * FROM [dbo].[TB_CONFIG_INVENTARIO];
